replicaCount: 2

image:
  repository: kanupriya18/registration-form
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
